WSGISocketPrefix /run/httpd/wsgi

WSGIDaemonProcess noggin processes=4 threads=1 maximum-requests=500 \
  display-name=%{GROUP} socket-timeout=2147483647 \
  lang=C.UTF-8 locale=C.UTF-8 \
  python-home=/srv/venv \
  python-path=/home/vagrant/noggin

WSGIScriptAlias /noggin /srv/noggin.wsgi
WSGIScriptReloading Off

<Location "/noggin">
  WSGIProcessGroup noggin
  WSGIApplicationGroup noggin
  Require all granted
  Header always append X-Frame-Options DENY
  Header always append Content-Security-Policy "frame-ancestors 'none'"
  Header unset Set-Cookie
  Header unset ETag
  FileETag None
</Location>