---
- name: Install RPM packages
  dnf:
    # enablerepo: updates-testing
    name:
      - ipsilon
      - ipsilon-tools-ipa
      - ipsilon-saml2
      - ipsilon-openid
      - ipsilon-openidc
      - ipsilon-authgssapi
      - ipsilon-authpam
      - ipsilon-infofas
      - ipsilon-theme-Fedora
      - httpd
      - krb5-workstation
      - fasjson-client
      - sqlite
      - openssl
      - git
      - patch
    state: present

- name: Install the bashrc
  copy:
    src: bashrc
    dest: /etc/profile.d/vagrant-ipsilon.sh
    mode: 0644
    owner: root
    group: root

- name: Download Fedora-specific code
  git:
    repo: https://pagure.io/fedora-infra/ipsilon-fedora.git
    dest: /opt/ipsilon-fedora
    force: yes

- name: Install Fedora-specific code
  command:
    cmd: ./install.sh
    chdir: /opt/ipsilon-fedora
    creates: /usr/lib/python{{ ansible_local["python"]["py3"]["version"] }}/site-packages/ipsilon/providers/openidc/plugins/account-scopes.py

- name: kinit
  shell: echo "{{ ipa_admin_password }}" | kinit {{ ipa_admin_user }}@{{ krb_realm }}


- name: install ipsilon
  command:
    cmd:  ipsilon-server-install
          --secure no
          --server-debugging
          --admin-user={{ ipa_admin_user }}
          --ipa=yes
          --openidc=yes
          --openid=yes
          --saml2=yes
    creates: /etc/ipsilon/idp/ipsilon.conf

- name: overwrite ipsilon configuration
  copy:
    src: "ipsilon.conf"
    dest: "/etc/ipsilon/idp/ipsilon.conf"
    owner: ipsilon
    group: ipsilon
    mode: 0600

# the configuration.conf template uses this to populate
# the openidc keyid
- name: get openidc key
  ansible.builtin.slurp:
    src: /var/lib/ipsilon/idp/openidc/openidc.key
  register: openidckey

- name: copy ipsilon admin configuration
  template:
    src: "configuration.conf"
    dest: "/etc/ipsilon/idp/configuration.conf"
    owner: ipsilon
    group: ipsilon
    mode: 0600

- name: configure SSLCertificateFile in ssl.conf
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: "SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt"
    line: SSLCertificateFile /etc/pki/tls/certs/server.pem

- name: configure SSLCertificateKeyFile in ssl.conf
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: "SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key"
    line: SSLCertificateKeyFile /etc/pki/tls/private/server.key

- name: fix the permissions of the keytab file
  file:
    name: /etc/httpd/conf/http.keytab
    owner: ipsilon

- name: set default client keytab in krb5.conf
  lineinfile:
    path: /etc/krb5.conf
    insertafter: 'default_ccache_name.*'
    line: '  default_client_keytab_name = FILE:/etc/httpd/conf/http.keytab'

- name: Tune SELinux Policy
  seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
  with_items:
    - httpd_can_connect_ldap
    - httpd_can_network_connect
    - httpd_use_fusefs

- name: Remove default static alias from httpd conf
  replace:
    path: /etc/ipsilon/idp/idp.conf
    regexp: '^\s*Alias \/idp\/ui \/usr\/share\/ipsilon\/ui'
    replace: '#Alias /idp/ui /usr/share/ipsilon/ui'

- name: Add static alias for Fedora theme in httpd conf
  lineinfile:
    path: /etc/ipsilon/idp/idp.conf
    insertbefore: BOF
    line: Alias /idp/ui /usr/share/ipsilon/themes/Fedora

- name: Add static alias for Fedora theme in httpd conf
  lineinfile:
    path: /etc/ipsilon/idp/idp.conf
    insertbefore: BOF
    line: Alias /ui /usr/share/ipsilon/themes/Fedora

- name: Set ipsilon theme to fedora
  lineinfile:
    path: /etc/ipsilon/idp/ipsilon.conf
    insertafter: 'template_dir = "templates"'
    line: 'theme_dir = "/usr/share/ipsilon/themes/Fedora"'

- name: Set CORS
  copy:
    src: cors.conf
    dest: /etc/httpd/conf.d/cors.conf


- name: Allow apache to access the public directory
  file:
    path: /var/lib/ipsilon/idp
    group: apache
    mode: g+x
    state: directory

- name: Allow access to the public directory
  file:
    path: /var/lib/ipsilon/idp/public
    mode: a+rX
    state: directory
    recurse: yes

- name: Make IPA's cert available publicly
  copy:
    src: /etc/ipa/ca.crt
    dest: /var/www/html/ca.crt
    remote_src: yes

- name: Enable and restart Apache
  systemd:
    state: restarted
    name: httpd
    enabled: yes
    daemon_reload: yes
